## List type variables

- name: Variables
  hosts: localhost
  vars:
    name:
      - revanth.txt
      - madhu.txt
      - reddy.txt
  tasks:
    - name: 
      file:
        path: ./{{name[1]}}
        state: touch



## Dictionary variables
- name: Variables
  hosts: localhost
  vars:
    name: madhu.txt
    ip: 192.168.0.100
    username:
      name: madhu
      domain: cloudops
  tasks:
    - name: 
      file:
        path: ./{{username['domain']}}
        state: touch

### with_items 

---
- hosts: all
  become: yes
  tasks:
    - name: Install applications
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - sqlite
        - jq
~    

- hosts: all
  become: yes
  tasks:
    - name: Set up user
      user:
        name: "admin"
        password: "secret_pass"
        comment: "admin@example.com"
        state: present


user_details={'username': 'admin', 'password': 'secret_pass', 'email': 'admin@example.com'}




---
- hosts: localhost
  tasks:
    - shell: cat /etc/resolv.conf
      register: result
    - debug:
        msg: '{{result}}'


