## List type variables

- name: Variables
  hosts: localhost
  vars:
    name:
      - revanth.txt
      - madhu.txt
      - reddy.txt
  tasks:
    - name: 
      file:
        path: ./{{name[1]}}
        state: touch



## Dictionary variables
- name: Variables
  hosts: localhost
  vars:
    name: madhu.txt
    ip: 192.168.0.100
    username:
      name: madhu
      domain: cloudops
  tasks:
    - name: 
      file:
        path: ./{{username['domain']}}
        state: touch