- name: Variables
  hosts: localhost
  vars:
    name:
      - revanth.txt
      - madhu.txt
      - reddy.txt
  tasks:
    - name: 
      file:
        path: ./{{name[1]}}
        state: touch




- name: Variables
  hosts: localhost
  vars:
    name: madhu.txt
    ip: 192.168.0.100
  tasks:
    - name: 
      file:
        path: ./{{name}}
        state: touch