- name: Variables
  hosts: all
  vars:
    dns_server: 10.1.250.10
  tasks:
    - name: 
      lineinfile: /etc/resolv.conf
      line: 'name server {{dns_server}}'



- name: Variables
  hosts: all
  vars:
    ip: 10.2.2.0
    name: "Madhu"
    packages:
      - nginx
        postgresql
        git
  tasks:
    - name: 
      file:
        path: /tmp/madhu.txt
        state: touch
    



# dns_server: 10.1.250.10 

# In variables file